# ==============================================================================
# CONFIGURACIÓN DE LAZYGIT (TEMA STATIC NOISE & DELTA INTEGRATION)
# ==============================================================================

gui:
  theme:
    activeBorderColor:
      - '#72EAD5' # Cyan dominante para el panel enfocado
      - bold
    inactiveBorderColor:
      - '#343A4A' # Borde border tenue y discreto para paneles inactivos
    searchingActiveBorderColor:
      - '#F3A261' # Orange para búsqueda activa
      - bold
    optionsTextColor:
      - '#72EAD5'
    selectedLineBgColor:
      - '#193C3B' # cyanDim de alto contraste para selección activa
    cherryPickedCommitBgColor:
      - '#332B4D' # purpleDim para commits cherry-pick
    cherryPickedCommitFgColor:
      - '#72EAD5'
    unstagedChangesColor:
      - '#EF7785' # Red para cambios sin staged
    defaultFgColor:
      - '#E6E2D6' # Text
  showIcons: true
  nerdFontsVersion: "3"
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never --line-numbers
