# ==============================================================================
# CONFIGURACIÓN DE LAZYGIT (TEMA TOKYONIGHT HIGH-CONTRAST & DELTA INTEGRATION)
# ==============================================================================

gui:
  theme:
    activeBorderColor:
      - '#7dcfff' # Cyan brillante para el panel enfocado
      - bold
    inactiveBorderColor:
      - '#292e42' # Borde tenue y discreto para paneles inactivos
    searchingActiveBorderColor:
      - '#ff9e64'
      - bold
    optionsTextColor:
      - '#7dcfff'
    selectedLineBgColor:
      - '#3d59a1' # Azul Tokyonight de alto contraste
    cherryPickedCommitBgColor:
      - '#2e3c64'
    cherryPickedCommitFgColor:
      - '#7dcfff'
    unstagedChangesColor:
      - '#f7768e'
    defaultFgColor:
      - '#c0caf5'
  showIcons: true
  nerdFontsVersion: "3"
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never --line-numbers
